const types = {
  PLAY: 'PLAY',
  SET_CLOCK: 'SET_CLOCK',
  SHUFFLE: 'SHUFFLE',
  ADD_CARD_ACTIVE: 'ADD_CARD_ACTIVE',
  DELETE_CARD_ACTIVE: 'DELETE_CARD_ACTIVE',
  CLEAR_CARD_ACTIVE: 'CLEAR_CARD_ACTIVE',
  RESET: 'RESET',
};

export default types;
